fix: update icons to paths
zendeskgarden/svg-icons pull request #201
Opened 2020-12-03 19:25 UTC by rossmoody

- [ ] **BREAKING CHANGE?** 

## Description

This PR amends 16 icons to paths instead of stroke to stop them from disappearing when a user zooms.

12 and 16px versions of:

- `copy-stroke`
- `email-stroke`
- `table-stroke`
- `translation-updated-stroke`
- `translation-deleted-stroke`
- `translation-created-stroke`
- `translation-outdated-stroke`
-` translation-exists-stroke`

## Detail

## Checklist

* [ ] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [ ] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [ ] :black_medium_small_square: Renders as expected in "dark" mode
* [ ] :white_large_square: Renders as expected @ 2x scale

2020-12-03 21:25 UTC, ginnywood approved these changes
Looks good to me. @rossmoody are you going to update the Sketch symbols too? It’d be good if those matched this treatment.

2020-12-03 22:02 UTC, rossmoody commented
@ginnywood All I did in this case was export the icons with the strokes outlined, but when I opened the icons file in Sketch they were already outlined so made the job pretty easy.

2020-12-03 23:43 UTC, jzempel requested changes
Looks like a few random `fill` attributes crept in.

2020-12-03 23:43 UTC, jzempel commented on src/12/translation-updated-stroke.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="none" focusable="false" viewBox="0 0 12 12">
The `fill="none"` attribute should be removed from this line.

2020-12-03 23:43 UTC, jzempel commented on src/12/translation-deleted-stroke.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="none" focusable="false" viewBox="0 0 12 12">
The `fill="none"` attribute should be removed from this line.

2020-12-03 23:43 UTC, jzempel commented on src/12/translation-created-stroke.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="none" focusable="false" viewBox="0 0 12 12">
The `fill="none"` attribute should be removed from this line.

2020-12-04 00:18 UTC, jzempel approved these changes

2020-12-04 00:18 UTC, merged