feat: add sandbox and transfer icons
zendeskgarden/svg-icons pull request #220
Opened 2021-03-25 20:26 UTC by steue

- [ ] **BREAKING CHANGE?** 

## Description

Adds the following icons:

- `12/sandbox-stroke.svg`
- `12/sandbox-fill.svg`
- `16/sandbox-stroke.svg`
- `16/sandbox-fill.svg`
- `12/phone-call-transfer-only-stroke.svg`
- `12/phone-call-transfer-only-fill.svg`
- `16/phone-call-transfer-only-stroke.svg`
- `16/phone-call-transfer-only-fill.svg`

## Detail

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

2021-03-25 20:44 UTC, jzempel requested changes

2021-03-25 20:44 UTC, jzempel commented on src/12/sandbox-fill.svg
> +  <g fill="none">
Please remove this unnecessary `g`roup.

2021-03-25 20:44 UTC, jzempel commented on src/12/sandbox-stroke.svg
> +  <g fill="none">
Please remove this unnecessary `g`roup.

2021-03-25 20:44 UTC, jzempel commented on src/16/sandbox-fill.svg
> +  <g fill="none">
Please remove this unnecessary `g`roup.

2021-03-25 20:44 UTC, jzempel commented on src/16/sandbox-stroke.svg
> +  <g fill="none">
Please remove this unnecessary `g`roup.

2021-03-25 21:41 UTC, steue commented on src/16/sandbox-stroke.svg
> +  <g fill="none">
ah! great catch. thank you jz! ⚡️ 💪

2021-03-25 22:05 UTC, jzempel approved these changes

2021-03-30 15:46 UTC, nyckie approved these changes

2021-03-30 20:25 UTC, jzempel commented
- `12/sandbox-stroke.svg`
- `12/sandbox-fill.svg`
- `16/sandbox-stroke.svg`
- `16/sandbox-fill.svg`
- `12/phone-call-transfer-only-stroke.svg`
- `12/phone-call-transfer-only-fill.svg`
- `16/phone-call-transfer-only-stroke.svg`
- `16/phone-call-transfer-only-fill.svg`

2021-03-30 20:25 UTC, merged