feat: add new parentheses and pin icons
zendeskgarden/svg-icons pull request #261
Opened 2022-01-24 15:59 UTC by steue

- [ ] **BREAKING CHANGE?** 

## Description

Adds new icons:

parentheses
- 12/parentheses-fill
- 12/parentheses-stroke
- 16/parentheses-fill
- 16/parentheses-stroke

pin and pin-remove
- 12/pin-fill
- 12/pin-stroke
- 12/pin-remove-fill
- 12/pin-remove-stroke
- 16/pin-fill
- 16/pin-stroke
- 16/pin-remove-fill
- 16/pin-remove-stroke

## Details
![image](https://user-images.githubusercontent.com/39511661/150817217-f3e80b6e-8734-45e8-8230-1f4e6ee3bd93.png)
![image](https://user-images.githubusercontent.com/39511661/150817145-1dd9ff0a-64db-4cbf-add3-a237d715ed24.png)

## Checklist

* [x] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [x] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [x] :black_medium_small_square: Renders as expected in "dark" mode
* [x] :white_large_square: Renders as expected @ 2x scale

2022-01-24 21:20 UTC, jzempel requested changes
- Please remove the `src/.DS_Store` file that got checked in. We don't add OS-specific files to Garden repos.
- All the multiple `<path>` can be combined for SVG optimization
- All the `<g>` should be removed for optimization

@steue I'm happy to take this branch over for you if you want me to make these updates.

2022-01-24 23:26 UTC, steue commented
> * Please remove the `src/.DS_Store` file that got checked in. We don't add OS-specific files to Garden repos.
> * All the multiple `<path>` can be combined for SVG optimization
> * All the `<g>` should be removed for optimization
> 
> @steue I'm happy to take this branch over for you if you want me to make these updates.

hey @jzempel thanks for the review and for catching those bits! i tried using our usual formatting/optimization scripts, but as you can see those tweaks still need to be made. i'm wondering if it has to do with how figma calculates svgs and pathing vs sketch? 🤔 i don't think i've had to worry about those before.

i think it'd be helpful to take over for now. could we also set up some time to walk through what could be happening? 🎓 it'll be helpful for updating our figma > svg exporting workflow.

2022-01-25 15:22 UTC, jzempel approved these changes

2022-01-26 08:08 UTC, steue reviewed
thanks so much for cleaning these up jz! i'll work on documenting the lint to look out for. i'll also explore what we can do on the figma side in terms of optimization e.g. plugins

2022-01-26 15:22 UTC, Francois-Esquire approved these changes

2022-01-26 17:08 UTC, hzhu approved these changes

2022-02-04 17:45 UTC, nyckie approved these changes

2022-02-04 18:02 UTC, merged