feat: added camera icons and fixed formatting errors
zendeskgarden/svg-icons pull request #267
Opened 2022-04-06 15:58 UTC by bethanybeech

- [ ] **BREAKING CHANGE?** 

## Description

Added 16px and 12px stroke and fill versions of the camera icon

## Detail

## Checklist

* [ ] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [ ] :globe_with_meridians: SVG demo is up-to-date (`yarn start`)
* [ ] :black_medium_small_square: Renders as expected in "dark" mode
* [ ] :white_large_square: Renders as expected @ 2x scale

2022-04-06 16:00 UTC, Francois-Esquire commented on .gitignore
> +.DS_Store
```suggestion
```

2022-04-06 17:45 UTC, jzempel requested changes
it would be good to eek out a bit of cost savings on the size by combining `path` elements into one. lmk if you'd like me to make these optimizations.

2022-04-06 17:45 UTC, jzempel commented on .gitignore
> +*.log
[nit] can we restore the newline at the end of this file? (ideally, it won't appear in the diff)

2022-04-11 16:39 UTC, bethanybeech commented
@jzempel if it's not too much trouble for you to make the reformatting changes, I will take you up on your offer! It's probably faster than me trying to figure it out :)

2022-04-11 20:55 UTC, jzempel approved these changes

2022-04-11 20:57 UTC, merged