replaced bird twitter icons with new twitter icon
zendeskgarden/svg-icons pull request #316
Opened 2023-10-11 20:13 UTC by eshet-hayil

- [ ] **BREAKING CHANGE?** 

## Description

## Detail

## Checklist

* [ ] :ok_hand: SVG updates are Garden Designer approved (add the
  designer as a reviewer)
* [ ] :globe_with_meridians: SVG demo is up-to-date (`npm start`)
* [ ] :black_medium_small_square: Renders as expected in "dark" mode
* [ ] :white_large_square: Renders as expected @ 2x scale

2023-10-11 20:32 UTC, steue requested changes
the icons look good to me! need to remove the `.DS_Store` files, but other than that, looks ready to go! good work

2023-10-11 20:32 UTC, steue commented on .DS_Store
These `src/.DS_Store` files snuck in here. these are OS specific files we dont include in our repos.

2023-10-11 20:32 UTC, steue commented on src/.DS_Store
same. remove.

2023-10-11 20:32 UTC, steue commented on src/12/.DS_Store
^

2023-10-11 20:44 UTC, geotrev reviewed
Other than the `.DS_Store` files, looks good. Will approve when those are gone. :)

2023-10-12 07:33 UTC, steue approved these changes
noice

2023-10-12 15:08 UTC, jzempel approved these changes
Great quality on the SVG source. Thanks.

2023-10-12 15:10 UTC, merged